set nocompatible
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
set bg=dark

if has("vms")
  set nobackup          " do not keep a backup file, use versions instead
else
endif
set history=50          " keep 50 lines of command line history
set ruler               " show the cursor position all the time
set showcmd             " display incomplete commands
set incsearch           " do incremental searching
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

set formatoptions=tcrq " See Help (complex)
set shiftround " when at 3 spaces, and I hit > ... go to 4, not 5
set noai
set nosmartindent " smartindent (filetype indenting instead)
set cindent " do c-style indenting

"" Whitespace
set softtabstop=4 " unify
set shiftwidth=4 " unify
set tabstop=4 " real tabs should be 4, but they will show with set list on
set expandtab " no real tabs please!
set copyindent " but above all -- follow the conventions laid before us
set preserveindent " but above all -- follow the conventions laid before us

"" Searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set paste " usefull for no stupid indent when copy/paste

